<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Microsoft.AspNetCore.TestHost" />
		<PackageReference Include="NSubstitute" />
		<PackageReference Include="Shouldly" />
		<PackageReference Include="TUnit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Results.MinimalApi\Results.MinimalApi.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="NSubstitute" />
		<Using Include="Shouldly" />
		<Using Include="Microsoft.AspNetCore.Http.Results" Alias="AspNetResults" />
		<Using Include="Microsoft.AspNetCore.Http.IResult" Alias="IAspNetResult" />
	</ItemGroup>

</Project>
