<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.Bcl.AsyncInterfaces.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.Build.Locator.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.IO.Redist.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Buffers.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Collections.Immutable.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.IO.Pipelines.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Memory.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Numerics.Vectors.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Runtime.CompilerServices.Unsafe.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Text.Encodings.Web.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Text.Json.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Threading.Tasks.Extensions.dll" />
    <Content Remove="E:\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.ValueTuple.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="Scriban" />
  </ItemGroup>

</Project>
