name: Publish to NuGet

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build in Release mode
        run: dotnet build --configuration Release --no-restore

      - name: Pack Results
        run: dotnet pack src/Results/Results.csproj --configuration Release --no-build --output ./nupkgs

      - name: Pack Results.FluentValidation
        run: dotnet pack src/Results.FluentValidation/Results.FluentValidation.csproj --configuration Release --no-build --output ./nupkgs
      
      - name: Pack Results.Messaging
        run: dotnet pack src/Results.Messaging/Results.Messaging.csproj --configuration Release --no-build --output ./nupkgs
      
      - name: Pack Results.MinimalApi
        run: dotnet pack src/Results.MinimalApi/Results.MinimalApi.csproj --configuration Release --no-build --output ./nupkgs

      - name: Pack Results.Optional
        run: dotnet pack src/Results.Optional/Results.Optional.csproj --configuration Release --no-build --output ./nupkgs


      - name: Push to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}